# This file is in the root 'inventory' folder and reads from a .env file in the same folder.
version: '3.8'

services:
  # The backend application service
  app:
    build: .
    ports:
      # Use the PORT variable from the .env file for the host and container port
      - "${PORT}:${PORT}"
    environment:
      # This MONGODB_URI is specific to the Docker network
      MONGODB_URI: mongodb://mongo:27017/inventory_app
      # These variables are read from the root .env file and passed into the container
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mongo

  # The MongoDB database service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
