# Specifies the version of the docker-compose file format
version: '3.8'

# Defines the services (containers) that make up our application
services:
  # Defines our Node.js application service
  app:
    # Tells Docker to build this service using the Dockerfile in the current directory
    build: .
    # Maps port 5000 on our computer to port 5000 inside the container
    ports:
      - "5000:5000"
    # Sets the environment variables for our Node.js app inside the container
    environment:
      # We use the service name 'mongo' as the hostname to connect to the database
      MONGODB_URI: mongodb://mongo:27017/inventory_app
      JWT_SECRET: your_super_secret_jwt_key_12345
      PORT: 5000
    # Tells Docker that our app depends on the 'mongo' service.
    # This ensures the database starts before our application does.
    depends_on:
      - mongo

  # Defines our MongoDB database service
  mongo:
    # Tells Docker to use the official MongoDB image from Docker Hub
    image: mongo:latest
    # Maps port 27017 on our computer to port 27017 inside the container.
    # This is optional but useful if you want to connect to the database from your computer.
    ports:
      - "27017:27017"
    # Creates a volume to persist database data.
    # It maps the './mongo-data' folder on our computer to the '/data/db' folder inside the container.
    # This ensures that even if we stop and remove the container, our data is safe.
    volumes:
      - mongo-data:/data/db

# Defines the named volume we used above
volumes:
  mongo-data:
